language: php

sudo: false

php:
    - 7.1
    - 7.2
    - 7.3

cache:
    directories:
        - $HOME/.composer/cache

env:
    matrix:
        - Laravel=~5.5.0 Orchestra=~3.5.0 OrchestraDB=~3.5.0 PHPUnit=~6.0
        - Laravel=~5.6.0 Orchestra=~3.6.0 OrchestraDB=~3.6.0 PHPUnit=~7.0
        - Laravel=~5.7.0 Orchestra=~3.7.0 OrchestraDB=~3.7.0 PHPUnit=~7.0
        - Laravel=~5.8.0 Orchestra=~3.8.0 OrchestraDB=3.8.x-dev PHPUnit=~7.0

before_script:
    - travis_retry composer self-update
    - travis_retry composer require "laravel/framework:${Laravel}" --no-update
    - travis_retry composer require "orchestra/testbench:${Orchestra}" --no-update --dev
    - travis_retry composer require "orchestra/database:${OrchestraDB}" --no-update --dev
    - travis_retry composer require "phpunit/phpunit:${PHPUnit}" --no-update --dev
    - travis_retry composer update --no-interaction --prefer-dist

script:
    - vendor/bin/phpunit
